Updated Catalog item types
SkylineCommunications/Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml pull request #16
Opened 2024-12-10 16:16 UTC by SLC-brechtseys

Updated to match with the types mentioned on https://docs.dataminer.services/user-guide/Cloud_Platform/Catalog/Register_Catalog_Item.html?q=slamodel#manifest-file

2024-12-11 15:18 UTC, jarno-lernou requested changes

2024-12-11 15:18 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "DOC" }, "ChatOps Extension", "Documentation")},
I believe we don't want documentation on the Catalog, hence my request to remove this.

2024-12-11 15:18 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "DISMACRO" }, "ChatOps Extension", "DIS Macro")},
I believe we don't want DIS Macro's on the Catalog as this is probably not easily deployable towards your Visual Studio DIS installation, hence my request to remove this.

2024-12-11 15:18 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "CF" }, "Custom Solution", "Companion File")},
I believe we don't want companion files on the Catalog, hence my request to remove this.

2024-12-11 15:18 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "F" }, "Automation", "Function Definition")},
Today there's no intention to have this available on the Catalog due to various limitations. Not excluded for the future, but I'm not sure if it will ever be successful on the Catalog.

2024-12-11 15:18 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "SC" }, "Scripted Connector", "Scriped Connector") },
I see "Scriped Connector"

2024-12-12 16:28 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "DOC" }, "ChatOps Extension", "Documentation")},
Agreed, can always be added in the future if needed.

2024-12-12 16:28 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "DISMACRO" }, "ChatOps Extension", "DIS Macro")},
Agreed, can always be added in the future if needed.

2024-12-12 16:30 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "F" }, "Automation", "Function Definition")},
Agreed, can always be added in the future if needed.

2024-12-12 16:30 UTC, janstaelensskyline commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "SC" }, "Scripted Connector", "Scriped Connector") },
This is a bug, it can be fixed.

2024-12-12 20:45 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "DOC" }, "ChatOps Extension", "Documentation")},
OK, let's change to Custom Solution for now.

2024-12-12 20:47 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "DISMACRO" }, "ChatOps Extension", "DIS Macro")},
It's not because we have a GitHub repository that it's meant to be on the Catalog (ref. comment @abelleite). For this one, I would only add it once it becomes relevant (which I would be surprised by), but that's my opinion. If you feel strongly about this, I'm ok to follow though..

2024-12-12 20:49 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "CF" }, "Custom Solution", "Companion File")},
The mentioned repository is empty. The second (and last one) is documentation and also not meant to be put on the catalog. We can keep this as Custom Solution, but I would really have my doubts if we have such repositories on the catalog ;).

2024-12-12 20:50 UTC, jarno-lernou commented on Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml/Constants.cs
> +            { new ArtifactType(new[] { "F" }, "Automation", "Function Definition")},
Ok, but then use "Custom Solution" as a Function is not Automation.

2024-12-16 12:55 UTC, jarno-lernou approved these changes

2025-01-06 09:58 UTC, merged